// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "fpclocksvrctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CFpclocksvrctrl1

IMPLEMENT_DYNCREATE(CFpclocksvrctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CFpclocksvrctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CFpclocksvrctrl1 operations
