// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "fp_clockctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CFp_clockctrl1

IMPLEMENT_DYNCREATE(CFp_clockctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CFp_clockctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CFp_clockctrl1 operations
