//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OEMClient.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_OEMCLIENT_DIALOG            102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_DLG_SYS_INFO                130
#define IDD_DLG_DEV_SN                  131
#define IDD_DLG_BELL_INFO               132
#define IDD_DLG_ENROLL_FRM              133
#define IDD_DLG_LOG                     135
#define IDD_DLG_SET_PASSTIME            136
#define IDD_DLG_LOCK_CTRL               137
#define IDC_COMBO1                      1000
#define IDC_CMB_MECHINE_ID              1000
#define IDC_CMB_EM                      1000
#define IDC_CMB_DAY_LIST                1000
#define IDC_CMB_LIST                    1000
#define IDC_BUTTON1                     1001
#define IDC_BTN_OPEN                    1001
#define IDC_BTN_GET_DEV_TIME            1001
#define IDC_BTN_SN                      1001
#define IDC_BTN_READ_BELL_SETTING       1001
#define IDC_BTN_SET_NAME                1001
#define IDC_BTN_RD_SLOG                 1001
#define IDC_BTN_GET_DOOR_STATUS         1001
#define IDC_BTN_PASSTIME_READ           1001
#define IDC_BTN_SET_DEV_TIME            1002
#define IDC_BTN_BACKUP_NUM              1002
#define IDC_CMB_WEEK_LIST               1002
#define IDC_BTN_PWR_OFF_DEV             1003
#define IDC_BTN_PRD_NUM                 1003
#define IDC_BTN_WEEKPASSTIME_READ       1003
#define IDC_BTN_PWR_ON_DEV              1004
#define IDC_CMB_DAY_LIST2               1004
#define IDC_COMBO2                      1005
#define IDC_CMB_DEVICE_TYPE             1005
#define IDC_BTN_DISABLE_DEV             1005
#define IDC_CMB_PRIVILEGE               1005
#define IDC_CMB_LCKGRP_DAY_LIST         1005
#define IDC_COMBO3                      1006
#define IDC_CMB_COM_INDEX               1006
#define IDC_CMB_BACKUPNUM               1006
#define IDC_BTN_LOCKGROUP_READ          1006
#define IDC_IPADDRESS1                  1007
#define IDC_IPADDR                      1007
#define IDC_EDIT1                       1008
#define IDC_EDIT_PORT                   1008
#define IDC_EDIT_SN                     1008
#define IDC_EDIT1_HOUR                  1008
#define IDC_EDIT_COMPANY_NAME           1008
#define IDC_EDIT_STARTTIME_HOUR1        1008
#define IDC_EDIT_VALUE                  1008
#define IDC_EDIT2                       1009
#define IDC_EDIT_PASSWORD               1009
#define IDC_EDIT_BACKUP_NUM             1009
#define IDC_EDIT_ENROLL_NUM             1009
#define IDC_EDIT_STARTTIME_MINUTE1      1009
#define IDC_EDIT3                       1010
#define IDC_EDIT_SER_PORT               1010
#define IDC_EDIT_PRD_CODE               1010
#define IDC_EDIT_ENROLL_NAME            1010
#define IDC_EDIT_ENDTIME_HOUR1          1010
#define IDC_EDIT4                       1011
#define IDC_EDIT_TIMELIMIT              1011
#define IDC_EDIT2_MINUTE                1011
#define IDC_EDIT_CARD_NUM               1011
#define IDC_EDIT_ENDTIME_MINUTE1        1011
#define IDC_BUTTON2                     1012
#define IDC_BTN_SYS_INFO                1012
#define IDC_EDIT3_HOUR                  1012
#define IDC_BTN_DEL_NAME                1012
#define IDC_BTN_RD_ALL_SLOG             1012
#define IDC_BTN_OPEN_DOOR               1012
#define IDC_EDIT_STARTTIME_HOUR2        1012
#define IDC_BTN_GET_DEVICE_INFO         1012
#define IDC_BUTTON3                     1013
#define IDC_BTN_OPEN_DEV_SN_DLG         1013
#define IDC_EDIT3_MINUTE                1013
#define IDC_BTN_GET_USR_NAME            1013
#define IDC_BTN_UDRD_SLOG               1013
#define IDC_BTN_AUTO_RECOVER            1013
#define IDC_EDIT_STARTTIME_MINUTE2      1013
#define IDC_BTN_SET_DEVICE_INFO         1013
#define IDC_BUTTON4                     1014
#define IDC_EDIT4_HOUR                  1014
#define IDC_BTN_GET_BELL_INFO           1014
#define IDC_BTN_SET_USR_NAME            1014
#define IDC_BTN_EMPTY_SLOG              1014
#define IDC_BTN_REBOOT                  1014
#define IDC_EDIT_ENDTIME_HOUR2          1014
#define IDC_BTN_GET_DEVICE_STATUS       1014
#define IDC_FP_CLOCKCTRL                1015
#define IDC_EDIT4_MINUTE                1015
#define IDC_EDIT_ENDTIME_MINUTE2        1015
#define IDC_STATIC_SYS_INFO             1016
#define IDC_EDIT5_HOUR                  1016
#define IDC_EDIT_STARTTIME_HOUR5        1016
#define IDC_CHECK_DISABLE               1017
#define IDC_EDIT5_MINUTE                1017
#define IDC_EDIT_STARTTIME_MINUTE5      1017
#define IDC_STATIC_INFO                 1018
#define IDC_EDIT6_HOUR                  1018
#define IDC_EDIT_ENDTIME_HOUR5          1018
#define IDC_CHECK1                      1019
#define IDC_EDIT_ENDTIME_MINUTE5        1019
#define IDC_CHECK2                      1020
#define IDC_EDIT_STARTTIME_HOUR4        1020
#define IDC_CHECK3                      1021
#define IDC_EDIT_STARTTIME_MINUTE4      1021
#define IDC_CHECK4                      1022
#define IDC_EDIT_ENDTIME_HOUR4          1022
#define IDC_CHECK5                      1023
#define IDC_EDIT_ENDTIME_MINUTE4        1023
#define IDC_CHECK6                      1024
#define IDC_EDIT_MON                    1024
#define IDC_CHECK7                      1025
#define IDC_EDIT_TUE                    1025
#define IDC_CHECK8                      1026
#define IDC_EDIT_WEN                    1026
#define IDC_EDIT6_MINUTE                1027
#define IDC_EDIT_THU                    1027
#define IDC_EDIT7_HOUR                  1028
#define IDC_EDIT_STARTTIME_HOUR3        1028
#define IDC_EDIT7_MINUTE                1029
#define IDC_EDIT_STARTTIME_MINUTE3      1029
#define IDC_EDIT8_HOUR                  1030
#define IDC_EDIT_ENDTIME_HOUR3          1030
#define IDC_EDIT8_MINUTE                1031
#define IDC_EDIT_ENDTIME_MINUTE3        1031
#define IDC_EDIT_CIRCLE_COUNT           1032
#define IDC_EDIT_FRI                    1032
#define IDC_BTN_WRITE_BELL_SETTING      1033
#define IDC_EDIT_SAT                    1033
#define IDC_EDIT1_MINUTE                1034
#define IDC_EDIT_USER_ID                1034
#define IDC_EDIT2_HOUR                  1035
#define IDC_EDIT_WEEK_ID                1035
#define IDC_STATIC_BELL_INFO            1036
#define IDC_EDIT_GROUP_ID               1036
#define IDC_BTN_ENROLL_MGMT             1037
#define IDC_EDIT_SUN                    1037
#define IDC_BTN_LOG_MGMT                1038
#define IDC_STATIC_ENROLL_INFO          1039
#define IDC_LIST1                       1040
#define IDC_BTN_GET_ENROLL_DATA         1041
#define IDC_BTN_SET_ENROLL_DATA         1042
#define IDC_BTN_RM_MANAGER              1043
#define IDC_BTN_MDF_PRIVILEGE           1044
#define IDC_BTN_CLEAR_ALL_DATA          1045
#define IDC_BTN_DEL_ENROLL_DATA         1046
#define IDC_LIST_REPORT                 1047
#define IDC_BTN_RD_GLOG                 1048
#define IDC_BTN_RD_ALL_GLOG             1049
#define IDC_BTN_UDRD_GLOG               1050
#define IDC_BTN_EMPTY_GLOG              1051
#define IDC_BTN_LOCK_CTRL               1052
#define IDC_BTN_SET_PASSTIME            1053
#define IDC_BTN_UNCOND_OPEN             1053
#define IDC_BTN_UNCOND_CLOSE            1054
#define IDC_BTN_CANCEL_WARN             1055
#define IDC_STATIC_LOG_DATA_INFO        1058
#define IDC_CHECK_READ_MASK             1059
#define IDC_BTN_UD_DOWNLOAD             1060
#define IDC_BTN_EMPTY_ENROLL_DATA       1061
#define IDC_BTN_UD_UPLOAD               1062
#define IDC_BTN_GET_ENROLL_INFO         1063
#define IDC_BTN_GET_ALL_ENROLL_DATA     1064
#define IDC_BTN_SET_ALL_ENROLL_DATA     1065
#define IDC_BTN_SEND_ALL_ENROLL_DATA    1066
#define IDC_BTN_DELETE_DB_DATA          1067
#define IDC_STATIC_PASSTIME_INFO        1069
#define IDC_BTN_PASSTIME_WRITE          1070
#define IDC_BTN_WEEKPASSTIME_WRITE      1071
#define IDC_STATIC_LOCKCTRL2            1073
#define IDC_EDIT5                       1074
#define IDC_EDIT_GROUP_VALUE            1074
#define IDC_BTN_LOCKGROUP_WRITE         1075
#define IDC_DATETIMEPICKER_START        1078
#define IDC_DATETIMEPICKER_END          1079
#define IDC_BTN_GET_USERCTRL            1080
#define IDC_BTN_SET_USER_CTRL           1081
#define IDC_BTN_DEL_USER_CTRL           1082
#define IDC_BTN_CLEAR_ALL_UCTRL         1083

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
