// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "fpreaderctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CFpreaderctrl1

IMPLEMENT_DYNCREATE(CFpreaderctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CFpreaderctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CFpreaderctrl1 operations
